baseURL = 'https://naimsolong.github.io/'
copyright = "2019 - {year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'Amirul Naim Mohd Solong'
enableRobotsTXT = true

# List Config
summaryLength= 15
paginate = 15

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

[params]
      postHog = 'phc_Tvy9Z3Su6lhmQmQ0ILU0UDuJagS2k90PhbANAV3ZqwD'
      tweetHandle = '@naimsolong'
      imageSEO = ''
